// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcwhcqlptwukalpqzhio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjd2hjcWxwdHd1a2FscHF6aGlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4MTQxMjcsImV4cCI6MjA1MjM5MDEyN30.WVfMat4p5KLfOCH1Ms-PItZVroo3VJ7qAOYIzwF-V1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'x-my-custom-header': 'pokeprizecheck.com'
    }
  }
});